CREATE OR REPLACE PROCEDURE VER_TRRABAJADOR_WHILE
IS
CURSOR C1 IS
  SELECT APELLIDO1, NVL(TO_CHAR(FECHANAC), 'INEXISTENTE') AS FECHANAC
    FROM TRABAJADORES
    ORDER BY APELLIDO1;
VREG C1%ROWTYPE;
BEGIN 
  --ABRO EL CURSOR PARA PODER USARLO
  OPEN C1;
  --LEO EL PRIMER EMPLEADO
  FETCH C1 INTO VREG;
  --COMPRUEBO SI LA TABLA ESTA VACIA
  IF C1%NOTFOUND THEN
    DBMS_OUTPUT.PUT_LINE('TABLA VACIA');
  ELSE
  --HAGO UNA REPETITIVA PARA TRATAR AL EMPLEADO
  --A EMPLEADO HASTA QUE LLEGE AL FINAL DEL CURSOR
    WHILE C1%FOUND LOOP
    --SACO POR PANTALLA PARA CADA EMPLEADO SU APELLIDO1 Y SU FECHA
    DBMS_OUTPUT.PUT_LINE('EL APELLIDO ES: '||REG.APELLIDO1||' Y SU FECHA DE NACIMIENTO');
    END LOOP;
END;
EXECUTE VER_TRABAJADOR_WHILE;